### ISSUE TITLE
Missing 0.0.1 for sbt 0.13

### ISSUE THREAD

**Issue by joprice** [plippe/sbt-awss3pages#17]
I don't see a release in bintray for sbt 0.13, although cross sbt versions are configured.

**Comment by plippe** [comment]
Thanks for the heads up. 
Will have a look right away.

**Comment by plippe** [comment]
`+`, for cross build, was missing.
Waiting for CI to pass, and I will merge https://github.com/plippe/sbt-awss3pages/pull/18.

**Comment by joprice** [comment]
Sweet! Thanks for the quick action

**Comment by joprice** [comment]
Actually, should that be `^` instead of `+`?

**Comment by plippe** [comment]
Yes, just saw that. `+` is for libs.

**Comment by plippe** [comment]
Hoping I won't need a third one: https://github.com/plippe/sbt-awss3pages/pull/19
Sorry for the delay.

**Comment by plippe** [comment]
- [2.10/0.13](https://bintray.com/package/files/plippe/sbt/sbt-awss3pages?order=asc&sort=name&basePath=com.github.plippe%2Fsbt-awss3pages%2Fscala_2.10%2Fsbt_0.13&tab=files)
-[2.12/1.0](https://bintray.com/package/files/plippe/sbt/sbt-awss3pages?order=asc&sort=name&basePath=com.github.plippe%2Fsbt-awss3pages%2Fscala_2.12%2Fsbt_1.0&tab=files)

Looking for the other versions

**Comment by plippe** [comment]
Actually I seems I have everything that should be there, https://bintray.com/sbt/sbt-plugin-releases/sbt-site#files/com.typesafe.sbt/sbt-site.

Hope it all works for you now.

**Comment by joprice** [comment]
Tried it and it works! Thanks for the quick help!
